#!/bin/bash
# 🌟 Google Cloud Setup for Sophia Platform
# Helps you configure billing and authentication

echo "🌟 Sophia Platform - Google Cloud Setup"
echo "========================================"

echo "📋 Step 1: Google Cloud Authentication"
echo "Run this command to login:"
echo "  gcloud auth login"
echo ""

echo "📋 Step 2: Set Your Project"
echo "If you don't have a project yet, create one:"
echo "  gcloud projects create YOUR-PROJECT-ID --name='Sophia Platform'"
echo ""
echo "Then set it as active:"
echo "  gcloud config set project YOUR-PROJECT-ID"
echo ""

echo "📋 Step 3: Enable Billing"
echo "You need to:"
echo "1. Go to: https://console.cloud.google.com/billing"
echo "2. Create or link a billing account"
echo "3. Associate it with your project"
echo ""

echo "📋 Step 4: Enable Required APIs"
echo "  gcloud services enable compute.googleapis.com"
echo "  gcloud services enable container.googleapis.com" 
echo "  gcloud services enable cloudbuild.googleapis.com"
echo "  gcloud services enable run.googleapis.com"
echo "  gcloud services enable firestore.googleapis.com"
echo ""

echo "📋 Step 5: Create Service Account for GitHub Actions"
echo "  gcloud iam service-accounts create sophia-deployer --display-name='Sophia Deployer'"
echo "  gcloud projects add-iam-policy-binding YOUR-PROJECT-ID --member='serviceAccount:sophia-deployer@YOUR-PROJECT-ID.iam.gserviceaccount.com' --role='roles/owner'"
echo "  gcloud iam service-accounts keys create sophia-key.json --iam-account=sophia-deployer@YOUR-PROJECT-ID.iam.gserviceaccount.com"
echo ""

echo "📋 Step 6: Add Secrets to GitHub"
echo "Go to your GitHub repo settings > Secrets and add:"
echo "- GCP_SA_KEY: (contents of sophia-key.json file)"
echo "- GCP_PROJECT_ID: YOUR-PROJECT-ID"
echo ""

echo "💫 Once complete, you can deploy with:"
echo "  ./scripts/prestige.sh"
echo ""

echo "🚀 For $200K startup credits, use the landing page:"
echo "  http://localhost:8080"
echo ""
echo "💻 BONUS: Create High-Performance VM with Your Credits"
echo "======================================================"
echo ""
echo "📋 Step 7: Create Powerful VM Instance"
echo "For Sophia's AI processing, create a high-memory VM:"
echo "  # Create n1-highmem-4 instance (26GB RAM, 4 vCPUs)"
echo "  gcloud compute instances create sophia-ai-vm \\"
echo "    --zone=us-central1-a \\"
echo "    --machine-type=n1-highmem-4 \\"
echo "    --image-family=ubuntu-2204-lts \\"
echo "    --image-project=ubuntu-os-cloud \\"
echo "    --boot-disk-size=100GB \\"
echo "    --boot-disk-type=pd-ssd \\"
echo "    --tags=http-server,https-server"
echo ""
echo "📋 Step 8: Configure Firewall (allow web traffic)"
echo "  gcloud compute firewall-rules create allow-sophia-web \\"
echo "    --allow tcp:5000,tcp:8080,tcp:80,tcp:443 \\"
echo "    --source-ranges 0.0.0.0/0 \\"
echo "    --description 'Allow Sophia Platform web traffic'"
echo ""
echo "📋 Step 9: Connect to Your VM"
echo "  gcloud compute ssh sophia-ai-vm --zone=us-central1-a"
echo ""
echo "📋 Step 10: Auto-Setup Sophia on VM"
echo "Once connected to your VM, run this single command:"
echo "  curl -sSL https://raw.githubusercontent.com/chosen8823/sophia/main/scripts/vm_setup.sh | bash"
echo ""
echo "🌟 VM Specs for AI Processing:"
echo "- 26GB RAM (perfect for large language models)"
echo "- 4 vCPUs (parallel AI processing)"
echo "- 100GB SSD (fast model loading)"
echo "- Ubuntu 22.04 LTS (stable AI environment)"
echo ""
echo "💰 Estimated Monthly Cost with Startup Credits:"
echo "- VM: ~$200/month (FREE with your $200K credits!)"
echo "- Storage: ~$20/month"
echo "- Network: ~$10/month"
echo "Total: ~$230/month (covered by startup credits for 2+ years!)"
