name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/manus-platform:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to VM
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_NAME }} \
            --zone ${{ secrets.GCP_VM_ZONE }} \
            --command "docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/manus-platform:${{ github.sha }} && \\
                      docker stop manus || true && \\
                      docker rm manus || true && \\
                      docker run -d --name manus -p 5000:5000 \\
                        gcr.io/${{ secrets.GCP_PROJECT_ID }}/manus-platform:${{ github.sha }}"
